### ISSUE TITLE
样式加载不上

### ISSUE THREAD

**Issue by gavinning** [dufu1991/stdf#1]
如题，按照首页文档上说的配置了，但样式始终加载不出来，能否出个详细点的配置说明

**Comment by dufu1991** [comment]
我明确两个点：
1. 是否正确配置了Tailwind？不使用STDF，你的项目能否正常使用Tailwind CSS？
2. 样式加载不出来是Tailwind编译的CSS文件都没有吗？
3. 如果是用Vite，样式加载不出来是在开发环境还是编译部署之后？如果是部署之后请确定Vite配置的 base 路径指向没问题。

**Comment by gavinning** [comment]
@dufu1991 使用vite初始化的项目，Tailwind正常加载了官网的Hello world!例子
@yuedanlabs 非常感谢，按照这个配置成功加载了STDF
@dufu1991 刚开始学习svelte，这个组件库非常刚需，老铁加油，可以再完善一下配置相关文档，加载不成功确实比较懵

**Comment by yuedanlabs** [comment]
@gavinning You're welcome, and congratulations !

**Comment by dufu1991** [comment]
确实是文档没写清楚，已经增加说明。

**Comment by dufu1991** [comment]
@gavinning 再使用过程中有什么问题或者觉得设计不合理或使用不方便的地方，欢迎多提意见。🤝🏻

**Comment by gavinning** [comment]
@dufu1991 初学svelte，STDF帮助很大👍🏻

**Comment by dufu1991** [comment]
增加了脚手架，可以直接创建，基本配置也内置了，省去了配置麻烦。
