### ISSUE TITLE
不考虑使用Typescript 吗？

### ISSUE THREAD

**Issue by atshelchin** [dufu1991/stdf#15]
使用Typescript 好处显而易见，

1. **静态类型检查**：TypeScript 是 JavaScript 的超集，它引入了静态类型系统，这在开发大型项目时特别有用。静态类型检查帮助开发者在编码阶段就能发现可能的错误，而不是在运行时。这样一来，可以大大减少因类型错误而导致的 bug，提高代码质量。

    ```typescript
    function greet(name: string) {
        console.log(`Hello, ${name}`);
    }

    greet(123); // Error: Argument of type 'number' is not assignable to parameter of type 'string'.
    ```

2. **自文档化**：TypeScript 的类型注解和接口可以帮助开发者理解变量和函数期望的输入。这种清晰的定义，使得代码更易于理解和维护。

    ```typescript
    interface User {
        name: string;
        age: number;
    }

    function greet(user: User) {
        console.log(`Hello, ${user.name}`);
    }
    ```

**Comment by dufu1991** [comment]
1. 区别于内管类中后台项目，个人不推荐将面向客户的移动 web 开发成大型项目，不管是包体积还是体验上都不好。
2. 小项目一般也不会有太多成员参与，自己写的代码多写几行逻辑清晰的注释。不写注释逻辑混乱，加上 TS 也会变成屎山。
3. 个人还是希望尽量保证此项目的 npm 包体积，加上 TS 无疑会增大很多。如果将组件中详细的双语注释全部去除，我相信此项目会是同类移动 web 组件库体积最小的。
4. 目前我正在将组件的 Props 按照 JSDoc 的格式修改注释，结合我开发的 VS Code 插件，使用的时候可以快速提示可选值等信息。
5. 目前我正在重构主题系统，预计过几天会发布大版本，而且 Svelte5 即将发布，后续肯定有需要适配新版 Svelte。目前不考虑增加 TS，如果社区反映统一且强烈会考虑。
6. 最重要的一点，我对 TS 不熟，让我写可能写不来，需要社区多多参与了。

**Comment by atshelchin** [comment]
感谢@dufu1919  写出这么好的ui库，完成度已经很高了，文档齐全。

1. 有没有一种可能，这个项目也能用于中后台的移动版本？
2. 类型相当于对Props做出了承诺或约束，之后不会轻易改遍它。当然用JSDoc 实现也可以，主要决定于你。
3. 编译后的代码类型都去掉了，并没有增加包的体积。其实我觉得很多显而易见的地方不需要写注释，还有就是注释没必要用双语来写。
4. 见2
5. 大版本有什么变动吗，我正准备在下个项目中引入stdf。
6. JSDOC 或 Typescript 选择一个都行，我建议是Typescript, 或者开个帖子让社区成员投投票。

**Comment by dufu1991** [comment]
大版本只是增加了多主题配置，使用方式一样。后续会考虑投票 TypeScript 还是 JSDoc。

**Comment by dufu1991** [comment]
0.4.2 已经对所有组件按照 JSDoc 增加了类型注释，主流 IDE 也都支持了，使用组件时将会有更好的类型提示，你也可以开启 checkJs 或使用 TS 对传入组件的 Props 做类型检测。

**Comment by dufu1991** [comment]
目前 next 版本已经支持 TypeScript，请食用。
