### ISSUE TITLE
Cell click behavior

### ISSUE THREAD

**Issue by yuedanlabs** [dufu1991/stdf#7]
目前是点击整个 cell任意地方都会触发开关，这在某些场景下是不合理的，因为这失去了按钮或者箭头所处位置的指示意义（往往看到按钮或者箭头，都会下意识的点击按钮或者箭头的位置）

希望只点击局部有开关的部位才会触发开关状态，比如点击右侧的按钮部位才会切换开关，而点击左侧的标题或者副标题等文字部分时不触发开关。

当然这是我的理解，也是我的需求，至于要不要这样还是需要作者思考取舍。

**Comment by dufu1991** [comment]
确实会有这种需求，比如一个 Cell 同时需要支持开关，又可能需要执行其他交互，当前带 Switch 的 Cell 只允许一种交互确实不够。

但是当一个 Cell 只有一个开关交互时，从交互的友好性上来看，我还是认为点击整个 Cell 都能触发开关比较好，因为一个开关区域对于粗壮的手指来说操作区域还是有点小。退而求其次，即使凭直觉点击开关区域也完全不影响用户预期与体验。

所以 STDF 准备增加一个 Props，使点击右侧与整个 Cell 是否分为两种情况由此 Props 决定，默认值还是当前方案。

不过还是需要强调，一个 Cell 触发两种方式其实对用户来说是有心理负担的。比如想象这种情况：一个同时带开关和右侧箭头的 Cell，点击开关区域执行开关，点击其他区域进入到下一级页面对此项做详细配置，但依我个人来看，这种情况下用户第一时间看到是会有疑惑的，可能还需要思考一下才明白需要点哪里，增加了心理负担。这种情况就应该把开关也放到下一级页面去统一处理。

**Comment by dufu1991** [comment]
另外说一下关于「因为这失去了按钮或者箭头所处位置的指示意义（往往看到按钮或者箭头，都会下意识的点击按钮或者箭头的位置）」这一点，开关确实可以作为一个点击区域触发交互，但是如果 Cell 带箭头，箭头只是为了给用户 「此 Cell 可点击」的交互暗示，那一点点区域对于手指触控来说是根本无法承载交互的。

**Comment by yuedanlabs** [comment]
基本同意你的以上观点，现在大多数的app 里的交互方案也是点击整个 cell 响应开关，可能也是经过大量实践后的选择

我并没有考虑类似 同时带开关和箭头的 cell 存在，因为在我的认知里，一个 cell 的作用要么是显示一个状态（无点击），要么是一个开关（点击开关触发状态改变），要么是进入另一个页面的跳转（箭头指示点击跳转）。所以基于此认知，看到开关下意思点开关，看到箭头下意思的点箭头，而不是开关和箭头同时存在的增加迷惑性。当然真实情况是也可能会有此种奇怪情况...

>  所以 STDF 准备增加一个 Props，使点击右侧与整个 Cell 是否分为两种情况由此 Props 决定，默认值还是当前方案。

总体上 我也认为组件点击整个 cell作为一种默认配置，增加一种可选项可以`关闭点击效果`或者`指定点击区域`会是一种更优的设计

不过 还是需要根据组件的复杂度来衡量取舍，毕竟如果做出来的适配方案太复杂反而不如直接另行手搓

**Comment by dufu1991** [comment]
v0.2.10 已经满足您的场景，请确认后关闭此 issue，感谢🙏
