### ISSUE TITLE
Can this be used with Svelte Native ?

### ISSUE THREAD

**Issue by shiftlabs1** [dufu1991/stdf#8]
Can this be used with svelte native ? or are there Dom specific libs that will cause compatibility issues

**Comment by yuedanlabs** [comment]
Yes

> 🔔 Early Warning
> STDF also applies to other projects in the Svelte ecosystem, such as SvelteKit, Svelte Native, etc. Please make sure you understand their basic principles.

You can find this warning on the bottom of home page https://stdf.design.

**Comment by dufu1991** [comment]
After careful study, the UI interface of Svelte Native is handed over to the Native platform for rendering, which may make STDF components not applicable. However, if you are using a WebView alone for loading, then using STDF should not be a problem. However, this approach is not significantly different from using the entire web ecosystem, except that it may have advantages in terms of size and performance in smaller HTML files. I will also update the website to remove this description and avoid any confusion.
